trigger:
- main  # Change this to your branch name if different

pool:
  name: 'Default'  # Uses your self-hosted agent

variables:
  TEST_NAME: "HELLO WORLD"  # Ensures TEST_NAME is set properly

steps:
- script: |
    python -m pip install --upgrade pip
    pip install robotframework-pabot
    pip install -r requirements.txt
  displayName: 'Install Dependencies (Including Pabot)'

- script: |
    echo Running test: %TEST_NAME%
    pabot --processes 2 --test %TEST_NAME% Tests/
  displayName: 'Run Robot Framework Tests in Parallel using Pabot'
